on: [push, pull_request]

name: Continuous integration

jobs:
  ci:
    name: Check if domains are sorted alphabetically
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check domain sorting
        run: |
          sh scripts/check_alphabetical_sorting.sh
